version: '2'
services:
    xuanha-app:
        image: xuanha
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xuanha-mysql:3306/xuanha?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    xuanha-mysql:
        extends:
            file: mysql.yml
            service: xuanha-mysql
